# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 330c441f11b2619d870bda1f9c2029929fd2a88efcc1a28bfb61c30666b1e22ecb3ea38396eedc99793c72debb9ab3072ea775ecfa883e71cdcd21c3efd14014
  my_email: "florian.mettetal@gmail.com"

test:
  secret_key_base: 1ed040a25523d590f0723c33aabd52dae432dccbf9b06b9c411a43439d85f29f224df655f6ff8eab060dcc2649c4449de7e5f92d98e175c00b6a77f537b6eccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  my_email: "florian.mettetal@gmail.com"